# Use root/example as user/password credentials
version: '3.1'

services:
  todo-api:
    build: .
    command: npm test
    environment:
      - mongourl=mongodb://root:example@mongo/

  mongo:
    image: mongo
    restart: always
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todo
