name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test todo
        run: docker-compose -f ./docker-compose.test.yaml up --exit-code-from todo-api --build